default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_DB_HOST") { '0.0.0.0' } %>
  username: <%= ENV.fetch("POSTGRES_DB_USER") { 'user' } %>
  password: <%= ENV.fetch("POSTGRES_DB_PASS") { 'password' } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB_NAME") { 'greenatom_development' } %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB_NAME") { 'greenatom_test' } %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB_NAME") { 'greenatom' } %>
